fix for:  call of overloaded ‘abs(double)’ is ambiguous
fix an isssue on old gcc version:
Error: call of overloaded ‘abs(double)’ is ambiguous.

Add cmath header from c++ so the compiler picks the correct std::abs function and is not looking at cstdlib abs function.